trigger: none

jobs:
- job: 'windows'
  displayName: 'Windows latest'
  pool:
    vmImage: 'windows-latest'
  steps:
  - pwsh: |
      Get-Command git*.exe | Format-Table -AutoSize | Out-String -Width 512
      Write-Host "PATH:"
      $env:PATH -split ";"
