trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: powershellProgress
  displayName: 'Progress Preference'
  pool:
    vmImage: 'windows-latest'
  steps:
  - pwsh: |
      $stopwatch =  [system.diagnostics.stopwatch]::StartNew()
      for ($i = 1; $i -le 10000; $i++ )
      {
        $percentComplete = ($i/100)
        Write-Progress -Activity "Test Progress" -Status "$percentComplete% Complete:" -PercentComplete $percentComplete
        Start-Sleep -Milliseconds 1
      }
      $stopwatch.Elapsed
    displayName: Default
  - pwsh: |
      $ProgressPreference = 'SilentlyContinue'

      $stopwatch =  [system.diagnostics.stopwatch]::StartNew()
      for ($i = 1; $i -le 10000; $i++ )
      {
        $percentComplete = ($i/100)
        Write-Progress -Activity "Test Progress" -Status "$percentComplete% Complete:" -PercentComplete $percentComplete
        Start-Sleep -Milliseconds 1
      }
      $stopwatch.Elapsed
    displayName: SilentlyContinue
  - pwsh: |
      $ProgressPreference = 'Continue'

      $stopwatch =  [system.diagnostics.stopwatch]::StartNew()
      for ($i = 1; $i -le 10000; $i++ )
      {
        $percentComplete = ($i/100)
        Write-Progress -Activity "Test Progress" -Status "$percentComplete% Complete:" -PercentComplete $percentComplete
        Start-Sleep -Milliseconds 1
      }
      $stopwatch.Elapsed
    displayName: Continue