trigger: none
pr: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

variables:
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/windows'

jobs:
- job: powerShellCore
  displayName: 'PowerShell Core Progress Preference'
  pool:
    vmImage: 'windows-latest'
  steps:
  - pwsh: |
      Write-Output $PSVersionTable | Select-Object -Property OS, Platform | Format-List
    displayName: Get PowerShell version
  - pwsh: |
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: Default
    workingDirectory: '$(scriptDirectory)'
  - pwsh: |
      $ProgressPreference = 'SilentlyContinue'
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: SilentlyContinue
    workingDirectory: '$(scriptDirectory)'
  - pwsh: |
      $ProgressPreference = 'Continue'
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: Continue
    workingDirectory: '$(scriptDirectory)'

- job: windowsPowerShell
  displayName: 'Windows PowerShell Progress Preference'
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      Write-Output $PSVersionTable | Select-Object -Property OS, Platform | Format-List
    displayName: Get PowerShell version
  - powershell: |
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: Default
    workingDirectory: '$(scriptDirectory)'
  - powershell: |
      $ProgressPreference = 'SilentlyContinue'
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: SilentlyContinue
    workingDirectory: '$(scriptDirectory)'
  - powershell: |
      $ProgressPreference = 'Continue'
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: Continue
    workingDirectory: '$(scriptDirectory)'

- job: azurePowerShellCore
  displayName: 'Azure PowerShell Core Progress Preference'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzurePowerShell@5
    displayName: 'Default'
    inputs:
      azureSubscription: my-azure-subscription
      scriptType: inlineScript
      inline: |
        .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
      azurePowerShellVersion: 'latestVersion'
      pwsh: true
      workingDirectory: '$(scriptDirectory)'
  - task: AzurePowerShell@5
    displayName: 'SilentlyContinue'
    inputs:
      azureSubscription: my-azure-subscription
      scriptType: inlineScript
      inline: |
        $ProgressPreference = 'SilentlyContinue'
        .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
      azurePowerShellVersion: 'latestVersion'
      pwsh: true
      workingDirectory: '$(scriptDirectory)'
  - task: AzurePowerShell@5
    displayName: 'Continue'
    inputs:
      azureSubscription: my-azure-subscription
      scriptType: inlineScript
      inline: |
        $ProgressPreference = 'Continue'
        .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
      azurePowerShellVersion: 'latestVersion'
      pwsh: true
      workingDirectory: '$(scriptDirectory)'

- job: azureWindowsPowerShell
  displayName: 'Azure Windows PowerShell Progress Preference'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzurePowerShell@5
    displayName: 'SilentlyContinue'
    inputs:
      azureSubscription: my-azure-subscription
      scriptType: inlineScript
      inline: |
        $ProgressPreference = 'SilentlyContinue'
        .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
      azurePowerShellVersion: 'latestVersion'
      pwsh: false
      workingDirectory: '$(scriptDirectory)'
  - task: AzurePowerShell@5
    displayName: 'Default'
    inputs:
      azureSubscription: my-azure-subscription
      scriptType: inlineScript
      inline: |
        .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
      azurePowerShellVersion: 'latestVersion'
      pwsh: false
      workingDirectory: '$(scriptDirectory)'
  - task: AzurePowerShell@5
    displayName: 'Continue'
    inputs:
      azureSubscription: my-azure-subscription
      scriptType: inlineScript
      inline: |
        $ProgressPreference = 'Continue'
        .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
      azurePowerShellVersion: 'latestVersion'
      pwsh: false
      workingDirectory: '$(scriptDirectory)'