trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: pathNotProtected
  displayName: 'PATH not protected'
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      echo ##vso[task.prependpath]%SYSTEM_ARTIFACTSDIRECTORY%
    displayName: update PATH
    name: trusted
  - script: |
      echo %PATH%
    displayName: PATH modified
  
- job: pathProtected
  displayName: 'PATH protected'
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      echo ##vso[task.prependpath]%SYSTEM_ARTIFACTSDIRECTORY%
    displayName: update PATH
    name: untrusted
    target:
      settableVariables: none
  - script: |
      echo %PATH%
    displayName: PATH not modified