name: protect-path-variable

trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: pathNotProtected
  displayName: 'PATH not protected'
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      set
      echo %PATH%
      echo "##vso[task.prependpath]$(hostPath);C:\"
      echo %PATH%
    displayName: update PATH
  - script: |
      echo %PATH%
    displayName: PATH modified
  
- job: pathProtected
  displayName: 'PATH protected'
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      echo %PATH%
      echo "##vso[task.prependpath]$(hostPath);C:\"
      echo %PATH%
    displayName: update PATH
    target:
      settableVariables:
      - notPATH
  - script: |
      echo %PATH%
    displayName: PATH not modified