trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

container: mcr.microsoft.com/windows/servercore:ltsc2022

steps:
- script: set