trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: 'hosted'
  displayName: 'Hosted pool'
  pool:
    name: 'Hosted'
  steps:
  - pwsh: |
      Write-Output $PSVersionTable | Select-Object -Property OS, Platform | Set-Variable osProperties 
      if (Get-Command Get-ComputerInfo -ErrorAction SilentlyContinue) {
        $osProperties | Add-Member -MemberType NoteProperty -Name WindowsProductName -Value (Get-ComputerInfo | Select-Object WindowsProductName)
      }
      $osProperties | Format-List
- job: 'nopool'
  displayName: 'No pool specified'
  steps:
  - pwsh: |
      Write-Output $PSVersionTable | Select-Object -Property OS, Platform | Format-List