trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:  
- job: 'warning'
  displayName: 'Warning message 1'
  pool:
    name: 'Hosted'
  steps:
  - pwsh: |
      echo "##[warning]This text will be rendered as a warning"
    displayName: '##[warning]'
    
- job: 'logWarning'
  displayName: 'Warning message 2'
  pool:
    name: 'Hosted'
  steps:
  - pwsh: |
      echo "##vso[task.logissue type=warning]This text will be rendered as a warning, and will be shown on the pipeline run summary"
    displayName: '##vso[task.logissue type=warning]'

- job: 'error'
  displayName: 'Error message 1'
  pool:
    name: 'Hosted'
  steps:
  - pwsh: |
      echo "##[error]This text will be rendered as an error"
    displayName: '##[error]'
    
- job: 'logError'
  displayName: 'Error message 2'
  pool:
    name: 'Hosted'
  steps:
  - pwsh: |
      echo "##vso[task.logissue type=error]This text will be rendered as an error, and will be shown on the pipeline run summary"
    displayName: '##vso[task.logissue type=error]'
  