trigger: none

jobs:
- job: 'windows'
  displayName: 'windows-latest image'
  pool:
    vmImage: 'windows-latest'
  steps:
  - pwsh: |
      Get-Command git*
      Get-Item env:PATH

- job: 'ubuntu'
  displayName: 'ubuntu-latest image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - pwsh: |
      Get-Command git*
      Get-Item env:PATH
