parameters:
- name: dotNetVersion
  displayName: .NET Version
  type: string
  default: '3.1.x'
- name: vmImage
  displayName: Agent image
  type: string
  default: 'windows-latest'
  values:
  - macos-latest
  - ubuntu-latest
  - windows-latest
trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: 'usedotnet'
  displayName: 'Use .NET SDK ${{ parameters.dotNetVersion }}'
  pool:
    name: 'Azure Pipelines'
    vmImage: '${{ parameters.vmImage }}'
  steps:
  - pwsh: dotnet --list-sdks
    displayName: 'List .NET SDKs'
  - task: UseDotNet@2
    displayName: 'Use .NET SDK ${{ parameters.dotNetVersion }}'
    inputs:
      version: '${{ parameters.dotNetVersion }}'
  - pwsh: dotnet --list-sdks
    displayName: 'List .NET SDKs'
