name: task-retry

parameters:
- name: divider
  displayName: Random integer should be a multiple of
  type: integer
  default: 5
- name: retryCount
  displayName: Retry count
  type: number
  default: 20

trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: retryDemo
  displayName: 'Retry demo'
  pool:
    name: 'Hosted'
  steps:
  - pwsh: |
      $randomNumber = (Get-Random -Minimum 0 -Maximum 100)
      $divider = ${{ parameters.divider }}
      if (!($randomNumber % $divider)) {
        throw "$randomNumber can't be divided by $divider"
      }
    retryCountOnTaskFailure: ${{ parameters.divider }}
