# Pipeline to test Service Connections

parameters:
- name: serviceConnection
  displayName: Override Service Connection
  type: string
  default: 'my-azure-subscription'
- name: storageAccountName
  displayName: Storage Account
  type: string
  default: '<from storageAccountName variable>'
- name: storageContainerName
  displayName: Storage Account Container
  type: string
  default: '<from storageContainerName variable>'

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

pr: none
trigger: none

variables:
- name: serviceConnection
  ${{ if eq(parameters.serviceConnection, '<from serviceConnection variable>') }}:
    value: $[ variables['serviceConnectionDefault'] ]
  ${{ else }}:
    value: '${{ parameters.serviceConnection }}'
- name: storageAccountName
  ${{ if eq(parameters.storageAccountName, '<from storageAccountName variable>') }}:
    value: $[ variables['storageAccountNameDefault'] ]
  ${{ else }}:
    value: '${{ parameters.storageAccountName }}'
- name: storageContainerName
  ${{ if eq(parameters.storageContainerName, '<from storageContainerName variable>') }}:
    value: $[ variables['storageContainerNameDefault'] ]
  ${{ else }}:
    value: '${{ parameters.storageContainerName }}'

jobs:
- job: azCopy
  displayName: 'Agent File Copy - $(serviceConnection)'
  pool:
    name: 'Azure Pipelines'
    vmImage: windows-latest
  steps:
  - pwsh: New-TemporaryFile | Copy-Item -Destination $(Build.ArtifactStagingDirectory)
    displayName: 'Generate artifact'

  # AzureFileCopy@6 uses Azure RBAC and supports Workload identity federation
  - task: AzureFileCopy@6
    displayName: "Copy artifacts to $(storageAccountName)"
    inputs:
      azureSubscription: $(serviceConnection) 
      blobPrefix: $(Build.BuildId)
      containerName: $(storageContainerName)
      destination: 'AzureBlob'
      sourcePath: $(Build.ArtifactStagingDirectory) 
      storage: $(storageAccountName)