# Pipeline to test Service Connections

parameters:
- name: serviceConnection
  displayName: Override Service Connection
  type: string
  default: 'my-azure-subscription'
- name: azModuleVersion
  displayName: Azure Module Version
  type: string
  default: 'latest'

name: ${{ parameters.azModuleVersion }}-$(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

pr: none
trigger: none

variables:
- name: serviceConnection
  ${{ if eq(parameters.serviceConnection, '<from serviceConnection variable>') }}:
    value: $[ variables['serviceConnectionDefault'] ]
  ${{ else }}:
    value: '${{ parameters.serviceConnection }}'
- name: azModuleVersion
  value: '${{ parameters.azModuleVersion }}'

jobs:
- job: azPowerShell
  displayName: 'Azure PowerShell'
  pool:
    name: 'Azure Pipelines'
    vmImage: ubuntu-latest
  steps:
  - task: AzurePowerShell@5
    displayName: 'Default'
    continueOnError: true
    inputs:
      azureSubscription: '$(serviceConnection)'
      scriptType: inlineScript
      inline: |
        Write-Host "`nAz modules loaded:"
        Get-Module -All | Where-Object -Property Name -Like Az.*

        Write-Host "`nAz module versions installed:"
        Get-Module -ListAvailable -Name Az

        if (Get-Command -Name Get-InstalledModule -ErrorAction SilentlyContinue) {
          Write-Host "`nAz module versions installed with PowerShellGet:"
          Get-InstalledModule Az -AllVersions -ErrorAction SilentlyContinue
        }
      pwsh: true
      failOnStandardError: true
  - task: AzurePowerShell@5
    displayName: 'latestVersion'
    continueOnError: true
    inputs:
      azureSubscription: '$(serviceConnection)'
      scriptType: inlineScript
      inline: |
        Write-Host "`nAz modules loaded:"
        Get-Module -All | Where-Object -Property Name -Like Az.*

        Write-Host "`nAz module versions installed:"
        Get-Module -ListAvailable -Name Az

        if (Get-Command -Name Get-InstalledModule -ErrorAction SilentlyContinue) {
          Write-Host "`nAz module versions installed with PowerShellGet:"
          Get-InstalledModule Az -AllVersions -ErrorAction SilentlyContinue
        }
      azurePowerShellVersion: 'latestVersion'
      pwsh: true
      failOnStandardError: true
  - task: AzurePowerShell@5
    displayName: 'Specified version'
    continueOnError: true
    inputs:
      azureSubscription: '$(serviceConnection)'
      scriptType: inlineScript
      inline: |
        Write-Host "`nAz modules loaded:"
        Get-Module -All | Where-Object -Property Name -Like Az.*

        Write-Host "`nAz module versions installed:"
        Get-Module -ListAvailable -Name Az

        if (Get-Command -Name Get-InstalledModule -ErrorAction SilentlyContinue) {
          Write-Host "`nAz module versions installed with PowerShellGet:"
          Get-InstalledModule Az -AllVersions -ErrorAction SilentlyContinue
        }
      azurePowerShellVersion: 'OtherVersion'
      preferredAzurePowerShellVersion: '$(azModuleVersion)'
      pwsh: true
      failOnStandardError: true
