parameters:
- name: serviceConnection
  displayName: Azure Service Connection Name
  type: string
  default: my-azure-subscription

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: terraformSingleStep
  displayName: 'Same step Azure CLI & Terraform'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    # - task: TerraformInstaller@0
    #   displayName: 'Install Terraform'
    #   inputs:
    #     terraformVersion: 'latest'
    - task: AzureCLI@2
      displayName: 'Terraform with Azure CLI task'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          # List environment variables
          # Get-ChildItem -Path Env: -Recurse -Include * | Sort-Object -Property Name
          Get-ChildItem -Path Env: -Recurse -Include ARM_*,AZURE_*,ENDPOINT_DATA_*,SYSTEM_*,TF_* | Sort-Object -Property Name

          Get-ChildItem -Path Env: -Recurse -Include ENDPOINT_DATA_* | Sort-Object -Property Name `
                                                                     | Select-Object -First 1 -ExpandProperty Name `
                                                                     | ForEach-Object { $_ -replace 'ENDPOINT_DATA_','' } `
                                                                     | Set-Variable serviceConnectionId

          if (!$serviceConnectionId) {
            Write-Error "Could not find service connection ID"
            exit 1
          }

          #                      /{{HostName}}/{{ProjectName}}/_apis/distributedtask/hubs/build/plans/{{PlanId}}/jobs/{{JobId}}/oidctoken?api-version=7.1-preview.1&serviceConnectionId={{ServiceConnectionId}}
          https://dev.azure.com/ericvan/PipelineSamples/_apis/distributedtask/hubs/build/plans/c810d511-1e6d-46ee-b7da-665adc47a41d/jobs/0df11829-723c-52be-8c23-8dd77e9ea2f9/oidctoken?api-version=7.1-preview.1&serviceConnectionId=0216fd8c-2fb5-4779-982f-0b62e9dab316
          # $env:ARM_OIDC_REQUEST_URL = "${env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI}${env:SYSTEM_TEAMPROJECT}/_apis/distributedtask/hubs/build/plans/${env:SYSTEM_PLANID}/jobs/${env:SYSTEM_JOBID}/oidctoken?api-version=7.1-preview.1&serviceConnectionId=${serviceConnectionId}"
          $env:ARM_OIDC_REQUEST_URL = "${env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI}${env:SYSTEM_TEAMPROJECT}/_apis/distributedtask/hubs/build/plans/${env:SYSTEM_PLANID}/jobs/${env:SYSTEM_JOBID}/oidctoken?api-version=7.1-preview.1"

          Write-Host "Requesting OIDC token from Azure DevOps REST API at $env:ARM_OIDC_REQUEST_URL"
          $env:ARM_OIDC_REQUEST_TOKEN = '$(System.AccessToken)'

          # Invoke-RestMethod -Headers @{
          #                     Authorization  = "Bearer $(System.AccessToken)"
          #                   } `
          #                   -Uri $env:ARM_OIDC_REQUEST_URL `
          #                   -Method Post

          Invoke-RestMethod -Headers @{
                              Authorization  = "Bearer $(System.AccessToken)"
                              "Content-Type" = "application/x-www-form-urlencoded"
                            } `
                            -Body @{
                                serviceConnectionId = $serviceConnectionId
                            } `
                            -Uri $env:ARM_OIDC_REQUEST_URL `
                            -Method Post

        addSpnToEnvironment: true
        useGlobalConfig: true
        failOnStandardError: true
        workingDirectory: '$(Build.SourcesDirectory)/deployment/terraform-service-connection'
