parameters:
- name: pool
  displayName: Agent Pool
  type: string
  default: Azure Pipelines
- name: serviceConnection
  displayName: Azure Service Connection Name
  type: string
  default: my-azure-subscription
- name: azLogout
  displayName: Logout from Azure CLI
  type: boolean
  default: true

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ parameters.serviceConnection }}-$(Build.BuildId)

trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: terraformSingleStep
  displayName: 'Same step Azure CLI & Terraform'
  pool:
    name: ${{ parameters.pool }}
    vmImage: 'ubuntu-latest'
  steps:
    - task: AzureCLI@2
      name: azureCLI
      displayName: 'Terraform Test with Azure CLI task'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          # List environment variables
          Get-ChildItem Env: | Sort-Object -Property Name | Format-Table

          # Run Terraform within task
          terraform init

          ./set_terraform_azurerm_vars.ps1
          # Logging out from Azure CLI
          if ($${{ parameters.azLogout }}) {
            az logout
            Write-Host "`nLogged out from Azure CLI"
          }

          # terraform test -verbose -filter='test.tftest.hcl'  

          # $oldToken = $env:ARM_OIDC_TOKEN
          # ./set_terraform_azurerm_vars.ps1 -RequestNewToken -SystemAccessToken $(System.AccessToken)
          # if ($env:ARM_OIDC_TOKEN -eq $oldToken) {
          #   throw "No new token acquired"
          # }

          # terraform test -verbose -filter='test2.tftest.hcl'

          Get-ChildItem *.tftest.hcl | ForEach-Object { 
            ./set_terraform_azurerm_vars.ps1 -RequestNewToken -SystemAccessToken $(System.AccessToken)
            Write-Host "Processing $($_.name)..."
            terraform test -verbose -filter='$($_.name)'
          }
        useGlobalConfig: true
        addSpnToEnvironment: true
        failOnStandardError: true
        workingDirectory: '$(Build.SourcesDirectory)/deployment/terraform-service-connection'

