# azure-pipelines.yml
trigger:
  branches:
    include:
    - '*'
    
extends:
  template: template.yml
  parameters:
    usersteps:
    - bash: echo bash
    - script: echo This step will be stripped out and not run!
    - pwsh: echo pwsh