# azure-pipelines.yml
trigger:
  branches:
    include:
    - '*'

extends:
  template: template.yml
  parameters:
    usersteps:
    # - task: MyTask@1
    - bash: echo bash
    - script: echo This step will be stripped out and not run!
    # - task: MyOtherTask@2