# template.yml
parameters:
- name: usersteps
  type: stepList
  default: []


jobs:
- job: secure_buildjob
  steps:
  - ${{ each step in parameters.usersteps }}:
    - ${{ each pair in step }}:
        ${{ if ne(pair.key, 'script') }}:
          ${{ pair.key }}: ${{ pair.value }}
        ${{ else }}:
          '${{ pair.value }}': error         
