pr: none
trigger: none

parameters:
- name: serviceConnection
  displayName: Override Service Connection
  type: string
  default: 'my-azure-subscription'
- name: acrName
  displayName: Azure Container Registry
  type: string
  default: 'ericvanimages'
- name: acrResourceGroup
  displayName: Azure Container Registry Resource Group
  type: string
  default: 'ericvan-common'
- name: repository
  displayName: Repository
  type: string
  default: 'pipelineagent/ubuntu-agent-tools'

resources:
  containers:
  - container: tools
    type: ACR
    azureSubscription: ${{ parameters.serviceConnection }}
    resourceGroup: ${{ parameters.acrResourceGroup }}
    registry: ${{ parameters.acrName }}
    repository: ${{ parameters.repository }}

jobs:
  job: test
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  steps:
  - script: echo |
      echo $(resources.container.tools.type)
      echo $(resources.container.tools.registry)
      echo $(resources.container.tools.repository)
      echo $(resources.container.tools.tag)
      echo $(resources.container.tools.digest)
      echo $(resources.container.tools.URI)
      echo $(resources.container.tools.location)