trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

# container: ubuntu:20.04
container: mcr.microsoft.com/azure-functions/python:4-python3.11

steps:
- bash: |
    # apt-get update
    # apt-get install azure-functions-core-tools-4
    func --version
    python -V
  displayName: 'Azure Functions Core Tools'