trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
# - job: funcTools
#   container: mcr.microsoft.com/azure-functions/python:4-python3.11
#   displayName: 'Use Azure Functions Python container image'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - bash: |
#       func --version
#       python -V
#     displayName: 'Azure Functions Core Tools'


# https://github.com/mariadb-corporation/mariadb-connector-odbc/blob/dd67939300b2b693e920a5a7e8dab0a2b98fba2c/azure-pipelines.yml#L135
- job: ubuntu
  container: ubuntu:20.04
  displayName: 'Use ubuntu:20.04 container image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: /tmp/docker exec -t -u 0 ubuntu:20.04 sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - bash: |
      apt-get install -y -qq --no-install-recommends \
        apt-transport-https \
        apt-utils \
        wget

      wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      apt-get update
      apt-get install azure-functions-core-tools-4
      func --version
      python -V
    displayName: 'Install Azure Functions Core Tools'