trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: ubuntu20
  container: mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04
  displayName: Use Ubuntu 20.04 image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: printenv
