trigger: none

jobs:
- job: 
  strategy:
    matrix:
      Ubuntu2204:
        vmImage: 'ubuntu-22.04'
      Ubuntu2404:
        vmImage: 'ubuntu-24.04'
      Windows:
        vmImage: 'windows-latest'
    maxParallel: 3
  pool:
    vmImage: $(vmImage)
  steps:
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
  - task: CargoAuthenticate@0
    continueOnError: true
    inputs:
      cargoServiceConnections: 'cargo-stub'
  - task: Bash@3
    condition: eq(variables['vmImage'], 'ubuntu-24.04')
    displayName: 'Install Mono'
    inputs:
      targetType: 'inline'
      script: |
        sudo apt install ca-certificates gnupg
        sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update      
  - task: MsBuild@1
    continueOnError: true
    inputs:
      # msbuildVersion: 'latest'
      msbuildVersion: '17.0'
      solution: '**/*.sln'
      msbuildArchitecture: 'x64'
      configuration: 'Release'
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    continueOnError: true
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
