trigger: none

jobs:
- job: 
  strategy:
    matrix:
      Ubuntu2204:
        vmImage: 'ubuntu-22.04'
      Ubuntu2404:
        vmImage: 'ubuntu-24.04'
      Windows:
        vmImage: 'windows-latest'
    maxParallel: 3
  pool:
    vmImage: $(vmImage)
  steps:
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
  - task: AndroidSigning@2
    continueOnError: true
    inputs:
      apkFiles: '**/*.apk'
      jarsign: true
      jarsignerKeystoreFile: 'pathToYourKeystoreFile'
      jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
      jarsignerKeystoreAlias: 'yourKeystoreAlias'
      jarsignerKeyPassword: '$(jarsignerKeyPassword)'
      zipalign: true
  - task: CargoAuthenticate@0
    continueOnError: true
    inputs:
      username: "$(CARGO_USERNAME)"
      password: "$(CARGO_PASSWORD)"
  - task: MsBuild@1
    continueOnError: true
    inputs:
      solution: '**/*.sln'
      msbuildArchitecture: 'x64'
      configuration: 'Release'
  - task: NuGetCommand@2
    continueOnError: true
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
