trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: ubuntu20
  container: ubuntu:20.04
  displayName: Use Azure Functions Python container image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: printenv

- job: funcTools
  container: mcr.microsoft.com/azure-functions/python:4-python3.11-core-tools
  displayName: Use Azure Functions Python container image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      func --version
      python -V
    displayName: 'Use Azure Functions Core Tools'
