trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

container: ubuntu:20.04

steps:
- script: printenv