trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: ubuntu2204
  pool:
    vmImage: 'ubuntu-22.04'
  steps:
  - bash: |
      echo Hello from Ubuntu 22.04
      lsb_release -d
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: ubuntu2404
  pool:
    vmImage: 'ubuntu-24.04'
  steps:
  - bash: |
      echo Hello from Ubuntu 24.04
      lsb_release -d
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: ubuntulatest
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      echo Hello from the latest version of Ubuntu available
      lsb_release -d
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: ubuntu24048core
  pool:
    name: 'GitHub-hosted Agents'
    vmImage: 'ubuntu-24.04-8-core'
  steps:
  - bash: |
      echo Hello from Ubuntu 24.04 8 core
      lsb_release -d
      echo "# cores: $(nproc)"
      free -h
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
      Write-Host "Number of logical processors: $([Environment]::ProcessorCount)"
      Write-Host "Installed memory (MB): $([Math]::Round((Get-ComputerInfo).CsTotalPhysicalMemory / 1MB))"
- job: ubuntu240416core
  pool:
    name: 'GitHub-hosted Agents'
    vmImage: 'ubuntu-24.04-16-core'
  steps:
  - bash: |
      echo Hello from Ubuntu 24.04 16 core
      lsb_release -d
      echo "# cores: $(nproc)"
      free -h
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
      Write-Host "Number of logical processors: $([Environment]::ProcessorCount)"
      Write-Host "Installed memory (MB): $([Math]::Round((Get-ComputerInfo).CsTotalPhysicalMemory / 1MB))"
