trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

parameters:
- name: containerImage
  displayName: Container Image
  type: string
  default: ubuntu:20.04

name: $(Date:yyyyMMdd)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ parameters.containerImage }}

jobs:
- job: ubuntu20
  container: ${{ parameters.containerImage }}
  displayName: Use Ubuntu ${{ parameters.containerImage }} image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: printenv
