trigger: none
# schedules:
# - cron: '0 1 * * *'
#   displayName: 'Nightly build (UTC)'
#   always: 'true'
#   branches:
#     include:
#     - main

jobs:
- job: stepoutput
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # - bash: |
  #     echo "##vso[task.setvariable variable=ipAddress;issecret=true]bash"
  #     echo "##vso[task.setvariable variable=mySecretVal;issecret=true]secretvalue"
  # - bash: |
  #     echo $(ipAddress)
  #     echo $(mySecretVal)

  - pwsh: |
      Invoke-RestMethod https://api.ipify.org | Set-Variable ipAddress
      Write-Host "IP Address: ${ipAddress}"
      Write-Output "##vso[task.setvariable variable=ipAddress]${ipAddress}"
    displayName: 'Detect client IP address'

  - pwsh: |
      $previousIPAddress = "$(ipAddress)"
      Write-Host "Previous IP Address: ${previousIPAddress}"
      Invoke-RestMethod https://api.ipify.org | Set-Variable ipAddress
      if ($previousIPAddress -ne $ipAddress) {
        throw "Detected IP address ${ipAddress} is different from {$previousIPAddress} detected in previous task"
      }
      Write-Host "IP Address: ${ipAddress}"
      Write-Output "##vso[task.setvariable variable=ipAddress]${ipAddress}"
      Start-Sleep -Seconds 120
    displayName: 'Detect client IP address'

  - pwsh: |
      $previousIPAddress = "$(ipAddress)"
      Write-Host "Previous IP Address: ${previousIPAddress}"
      Invoke-RestMethod https://api.ipify.org | Set-Variable ipAddress
      if ($previousIPAddress -ne $ipAddress) {
        throw "Detected IP address ${ipAddress} is different from {$previousIPAddress} detected in previous task"
      }
      Write-Host "IP Address: ${ipAddress}"
      Write-Output "##vso[task.setvariable variable=ipAddress]${ipAddress}"
      Start-Sleep -Seconds 120
    displayName: 'Detect client IP address'
