trigger: none
# schedules:
# - cron: '0 1 * * *'
#   displayName: 'Nightly build (UTC)'
#   always: 'true'
#   branches:
#     include:
#     - main

jobs:
- job: stepoutput
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # - bash: |
  #     echo "##vso[task.setvariable variable=ipAddress;issecret=true]bash"
  #     echo "##vso[task.setvariable variable=mySecretVal;issecret=true]secretvalue"
  # - bash: |
  #     echo $(ipAddress)
  #     echo $(mySecretVal)

  - pwsh: |
      # $previousIPAddress = "$(ipAddress)"
      $ipAddress = "a"
      Write-Host "Previous IP Address: ${previousIPAddress}"
      Write-Host "IP Address: ${ipAddress}"
      Write-Output "##vso[task.setvariable variable=ipAddress§]${ipAddress}"

  - pwsh: |
      $previousIPAddress = "$(ipAddress)"
      $ipAddress = "b"
      Write-Host "Previous IP Address: ${previousIPAddress}"
      Write-Host "IP Address: ${ipAddress}"
      Write-Output "##vso[task.setvariable variable=ipAddress]${ipAddress}"

  - pwsh: |
      $previousIPAddress = "$(ipAddress)"
      $ipAddress = "c"
      Write-Host "Previous IP Address: ${previousIPAddress}"
      Write-Host "IP Address: ${ipAddress}"
      Write-Output "##vso[task.setvariable variable=ipAddress]${ipAddress}"
