trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

variables:
  xcodeRoot: "/Applications/Xcode_13.2.app"

jobs:
- job: xcodeSelect
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: |
      echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'$(xcodeRoot)
      sudo xcode-select --switch $(xcodeRoot)/Contents/Developer