trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: macOS13
  pool:
    vmImage: 'macOS-13'
  steps:
  - bash: |
      echo Hello from macOS Ventura
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: macOS14
  pool:
    vmImage: 'macOS-14'
  steps:
  - bash: |
      echo Hello from macOS Sonoma
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: macOS15
  pool:
    vmImage: 'macOS-15'
  steps:
  - bash: |
      echo Hello from macOS Sequia
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: macOSlatest
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: |
      echo Hello from the latest stable macOS image available
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: macOS14arm64
  pool:
    vmImage: ' macos-14-arm64'
  steps:
  - bash: |
      echo Hello from macOS Sonoma on Apple Silicon
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: macOSInternalLatest
  pool:
    vmImage: 'macos-internal-latest'
  steps:
  - bash: |
      echo Hello from macOS on Apple Silicon
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
