trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: macOS11
  pool:
    vmImage: 'macOS-11'
  steps:
  - bash: |
      echo Hello from macOS Big Sur
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: macOS12
  pool:
    vmImage: 'macOS-12'
  steps:
  - bash: |
      echo Hello from macOS Monterey
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: macOS13
  pool:
    vmImage: 'macOS-13'
  steps:
  - bash: |
      echo Hello from macOS Ventura
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
- job: macOSlatest
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: |
      echo Hello from the latest version of macOS available
      sw_vers
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
