trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: macOS1014
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: |
      echo Hello from macOS Mojave
      sw_vers
- job: macOS1015
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - bash: |
      echo Hello from macOS Catalina
      sw_vers
- job: macOS11
  pool:
    vmImage: 'macOS-11'
  steps:
  - bash: |
      echo Hello from macOS Big Sur
      sw_vers
# - job: macOS12
#   pool:
#     vmImage: 'macOS-12'
#   steps:
#   - bash: |
#       echo Hello from macOS Monterey
#       sw_vers
- job: macOSlatest
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: |
      echo Hello from the latest version of macOS available
      sw_vers