parameters:
- name: pool
  displayName: Agent Pool
  type: string
  default: Azure Pipelines
- name: serviceConnection
  displayName: Override Service Connection
  type: string

trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

variables:
- name: serviceConnection
  value: coalesce('${{ parameters.serviceConnection }}', variables['subscriptionConnection'])

jobs:
- job: azureCLI
  displayName: 'AzureCLI'
  strategy:
    matrix:
      MacOS:
        scriptType: ps
        vmImage: 'macos-latest'
      Ubuntu:
        scriptType: ps
        vmImage: 'ubuntu-latest'
      Windows-PowerShell:
        scriptType: ps
        vmImage: 'windows-latest'
      Windows-pwsh:
        scriptType: pscore
        vmImage: 'windows-latest'
    maxParallel: 3
  pool:
    name: ${{ parameters.pool }}
    vmImage: $(vmImage)
  steps:
  - task: AzureCLI@2
    displayName: 'ARM Service Connection permissions'
    inputs:
      azureSubscription: '$(serviceConnection)' # Task property referencing Service Connection -------------------------------------------------------
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Write-Host "`n$($PSStyle.Bold)Service Connection name: '$(serviceConnection)'$($PSStyle.Reset) -----------------------------------------------"

        Get-ChildItem -Path Env: -Recurse -Include ENDPOINT_DATA_* | Sort-Object -Property Name `
                                                                   | Select-Object -First 1 -ExpandProperty Name `
                                                                   | ForEach-Object { $_ -replace 'ENDPOINT_DATA_','' } `
                                                                   | Set-Variable serviceConnectionId
        Write-Host "`nService Connection ID: ${serviceConnectionId}"

        Write-Host "`naz account show"
        az account show --query "user.name" -o tsv | Set-Variable appId
        az account show -o json | Out-File -FilePath azureAccount.json
        Get-Content azureAccount.json

        Write-Host "`n$($PSStyle.Bold)Service Connection role assignments:$($PSStyle.Reset) ---------------------------------------------------------------"
        az role assignment list --all --assignee $appId -o json | Out-File -FilePath roleAssignments.json
        Get-Content roleAssignments.json | ConvertFrom-Json `
                                         | Select-Object -Property roleDefinitionName, scope `
                                         | Sort-Object -Property roleDefinitionName
                                         | Format-Table -AutoSize -Wrap

        Write-Host "`n$($PSStyle.Bold)Service Connection Service Principal object:$($PSStyle.Reset) -------------------------------------------------------"
        az ad sp show --id $appId -o json | Out-File -FilePath servicePrincipal.json
        Get-Content servicePrincipal.json

        Write-Host "`n$($PSStyle.Bold)Subscriptions the Service Connection has access to:$($PSStyle.Reset) ------------------------------------------------"
        az account list --query "sort_by([].{Name:name, SubscriptionId:id}, &Name)" -o table
        
        Write-Host "`n$($PSStyle.Bold)Resource groups that the Service Connection has access to in subscription '$(az account show --query name -o tsv)':$($PSStyle.Reset) -------------"
        az group list --query "sort_by([].{Name:name, ResourceId:id}, &Name)" -o table
      workingDirectory: '$(Build.ArtifactStagingDirectory)'

  - publish: $(Build.ArtifactStagingDirectory)
    displayName: 'Publish json files'
    artifact: indentityInfo-$(System.PlanId)-$(System.JobId)

- job: azurePowerShell
  displayName: 'AzurePowerShell'
  strategy:
    matrix:
      MacOS:
        pwsh: true
        vmImage: 'macos-latest'
      Ubuntu:
        pwsh: true
        vmImage: 'ubuntu-latest'
      Windows-PowerShell:
        pwsh: false
        vmImage: 'windows-latest'
      Windows-pwsh:
        pwsh: true
        vmImage: 'windows-latest'
    maxParallel: 3
  pool:
    name: ${{ parameters.pool }}
    vmImage: $(vmImage)
  steps:
  - task: AzurePowerShell@5
    displayName: 'AzurePowerShell context'
    inputs:
      azureSubscription: '$(serviceConnection)'
      scriptType: inlineScript
      inline: |
        Get-AzContext Format-List
        Get-AzContext | Select-Object -ExpandProperty Subscription | Format-List

      azurePowerShellVersion: 'latestVersion'
      pwsh: $(pwsh)
      failOnStandardError: true
