parameters:
- name: pool
  displayName: Agent Pool
  type: string
  default: Azure Pipelines
- name: vmImage
  displayName: Image
  type: string
  default: ubuntu-latest
  values:
  - 'ubuntu-latest'
  - 'windows-latest'

trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: agent
  displayName: 'Show Azure Service Connection context'
  pool:
    name: ${{ parameters.pool }}
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: AzureCLI@2
    displayName: 'ARM Service Connection permissions'
    inputs:
      azureSubscription: '$(subscriptionConnection)' # Task property referencing Service Connection -------------------------------------------------------
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Write-Host "`n$($PSStyle.Bold)Service Connection name: '$(subscriptionConnection)'$($PSStyle.Reset) -----------------------------------------------"

        Get-ChildItem -Path Env: -Recurse -Include ENDPOINT_DATA_* | Sort-Object -Property Name `
                                                                   | Select-Object -First 1 -ExpandProperty Name `
                                                                   | ForEach-Object { $_ -replace 'ENDPOINT_DATA_','' } `
                                                                   | Set-Variable serviceConnectionId
        Write-Host "`nService Connection ID: ${serviceConnectionId}"

        Write-Host "`naz account show"
        az account show --query "user.name" -o tsv | Set-Variable appId
        az account show -o json | Out-File -FilePath azureAccount.json
        Get-Content azureAccount.json

        Write-Host "`n$($PSStyle.Bold)Service Connection role assignments:$($PSStyle.Reset) ---------------------------------------------------------------"
        az role assignment list --all --assignee $appId -o json | Out-File -FilePath roleAssignments.json
        Get-Content roleAssignments.json | ConvertFrom-Json `
                                         | Select-Object -Property roleDefinitionName, scope `
                                         | Sort-Object -Property roleDefinitionName
                                         | Format-Table -AutoSize -Wrap

        Write-Host "`n$($PSStyle.Bold)Service Connection Service Principal object:$($PSStyle.Reset) -------------------------------------------------------"
        az ad sp show --id $appId -o json | Out-File -FilePath servicePrincipal.json
        Get-Content servicePrincipal.json

        Write-Host "`n$($PSStyle.Bold)Subscriptions the Service Connection has access to:$($PSStyle.Reset) ------------------------------------------------"
        az account list --query "sort_by([].{Name:name, SubscriptionId:id}, &Name)" -o table
        
        Write-Host "`n$($PSStyle.Bold)Resource groups that the Service Connection has access to in subscription '$(az account show --query name -o tsv)':$($PSStyle.Reset) -------------"
        az group list --query "sort_by([].{Name:name, ResourceId:id}, &Name)" -o table
      workingDirectory: '$(Build.ArtifactStagingDirectory)'

  - task: AzurePowerShell@5
    displayName: 'AzurePowerShell context'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: inlineScript
      inline: |
        Get-AzContext Format-List
        Get-AzContext | Select-Object -ExpandProperty Subscription | Format-List

      azurePowerShellVersion: 'latestVersion'
      pwsh: true
      failOnStandardError: true

  - publish: $(Build.ArtifactStagingDirectory)
    displayName: 'Publish json files'
    artifact: indentityInfo