trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: agent
  displayName: 'Get Azure Service Connection Info'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    displayName: 'Display Identity information'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Write-Host "`$env:servicePrincipalId is set: '$($env:servicePrincipalId -ne $null)'"
        Write-Host "`$env:tenantId is set: '$($env:tenantId -ne $null)'"
        az account show --query "user.name" -o tsv | Set-Variable appId
        az account show -o json | Out-File -FilePath azureAccount.json
        Get-Content azureAccount.json

        Write-Host "Roles assignments for identity:"
        Write-Host "az role assignment list --all --assignee $($servicePrincipal.id))"
        az role assignment list --all --assignee $servicePrincipal.id -o json | Out-File -FilePath roleAssignments.json
        Get-Content roleAssignments.json

        Write-Host "Service Principal object:"
        Write-Host "az ad sp show --id ${appId}"
        az ad sp show --id $appId -o json | Out-File -FilePath servicePrincipal.json
        Get-Content servicePrincipal.json | ConvertFrom-Json | Set-Variable servicePrincipal
        Get-Content servicePrincipal.json

        Write-Host "These are subscriptions that identity has access to:"
        az account list --query "sort_by([].{Name:name, SubscriptionId:id}, &Name)" -o table
        
        Write-Host "These are resource groups that identity has access to in '$(az account show --query name -o tsv)':"
        az group list --query "sort_by([].{Name:name, ResourceId:id}, &Name)" -o table
      addSpnToEnvironment: true
      failOnStandardError: false
      workingDirectory: '$(Build.ArtifactStagingDirectory)'

  - publish: $(Build.ArtifactStagingDirectory)
    displayName: 'Publish json files'
    artifact: indentityInfo