parameters:
- name: intervalMinutes
  displayName: Interval (minutes)
  type: number
  default: 5
- name: maxMinutes
  displayName: Maximum time (minutes)
  type: number
  default: 360
  
trigger: none

jobs:
- job: agent
  displayName: 'ID Token Lifetime test'
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  timeoutInMinutes: ${{ parameters.maxMinutes }}
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(subscriptionConnection)
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $stopwatch = [system.diagnostics.stopwatch]::StartNew()
        do {
          Write-Host "`naz account show"
          az account show
          Write-Host "Elapsed time: $($stopwatch.Elapsed.TotalMinutes) minutes, sleeping for ${{ parameters.intervalMinutes }} minutes..."
          Start-Sleep -Seconds (60 * ${{ parameters.intervalMinutes }})
        } while ($stopwatch.Elapsed.TotalMinutes -lt (${{ parameters.maxMinutes }}-${{ parameters.intervalMinutes }}-1))

