parameters:
- name: intervalMinutes
  displayName: Interval (minutes)
  type: number
  default: 1
- name: maxMinutes
  displayName: Maximum time (minutes)
  type: number
  default: 5
  
trigger: none

jobs:
- job: agent
  displayName: 'ID Token Lifetime test'
  pool:
    name: Azure Pipelines' 
    vmImage: ubuntu-latest
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(subscriptionConnection)
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $stopwatch = [system.diagnostics.stopwatch]::StartNew()
        while ($stopwatch.Elapsed.TotalMinutes -lt ${{ parameters.maxMinutes }}) {
          Write-Host "`naz account show"
          az account show
          Write-Host "Elapsed time: $($stopwatch.Elapsed.TotalMinutes) minutes, sleeping for ${{ parameters.intervalMinutes }} minutes..."
          Start-Sleep -Duration (New-TimeSpan -Minutes ${{ parameters.intervalMinutes }})
        }

