trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main


variables:
- group: 'kubernetes' # should contain subscriptionConnection, aksId

jobs:
- job: agent
  displayName: 'Kubernetes tasks'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - pwsh: |
      $aksIdElements = '$(aksId)'.Split('/')
      Write-Host "##vso[task.setvariable variable=aksName;isOutput=true]$aksIdElements[8]"
      Write-Host "##vso[task.setvariable variable=resourceGroupName;isOutput=true]$aksIdElements[4]"
    name: split
    displayName: 'Display variables'

  - task: AzureCLI@2
    displayName: 'Access AKS'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks get-credentials -n $(split.aksName) -g $(split.resourceGroupName) -a

        kubectl config view
        kubectl cluster-info
        kubectl get nodes

  - task: AzureCLI@2
    displayName: 'Install kubelogin'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks install-cli --kubelogin-version latest
