trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main


variables:
- group: 'kubernetes' # should contain subscriptionConnection, aksId

jobs:
- job: agent
  displayName: 'Kubernetes tasks'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - pwsh: |
      $aksIdElements = '$(aksId)'.Split('/')
      $aksName = $aksIdElements[8]
      $resourceGroupName = $aksIdElements[4]
      Write-Host "aksId: $(aksId)"
      Write-Host "aksName: ${aksName}"
      Write-Host "resourceGroupName: ${resourceGroupName}"
      Write-Host "##vso[task.setvariable variable=aksName;isOutput=true]${aksName}"
      Write-Host "##vso[task.setvariable variable=resourceGroupName;isOutput=true]${resourceGroupName}"
    name: split
    displayName: 'Prepare variables'

  - task: AzureCLI@2
    displayName: 'Disable local accounts'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Write-Host "Disabling local accounts on $(split.aksName)..."
        az aks update -n $(split.aksName) -g $(split.resourceGroupName) --disable-local-accounts

  - task: AzureCLI@2
    displayName: 'kubectl (fails)'
    continueOnError: true 
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks get-credentials -n $(split.aksName) -g $(split.resourceGroupName) -a

        kubectl config view
        kubectl cluster-info
        kubectl get nodes

  - task: AzureCLI@2
    displayName: 'Enable local accounts'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Write-Host "Enabling local accounts on $(split.aksName)..."
        az aks update -n $(split.aksName) -g $(split.resourceGroupName) --enable-local-accounts

  - task: AzureCLI@2
    displayName: 'kubectl'
    continueOnError: true 
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks get-credentials -n $(split.aksName) -g $(split.resourceGroupName) -a

        kubectl config view
        kubectl cluster-info
        kubectl get nodes

  - task: AzureCLI@2
    displayName: 'Install kubelogin (fails)'
    continueOnError: true 
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks install-cli --kubelogin-version latest
