trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

variables:
- group: 'kubernetes' # should contain subscriptionConnection, aksId

jobs:
- job: inspectCluster
  displayName: 'Kubernetes access & disable local accounts'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - pwsh: |
      if ([string]::isNullOrEmpty('$(aksId)')) {
        Write-Error "aksId variable is not set"
        exit 1
      }
      $aksIdElements = '$(aksId)'.Split('/')
      if ($aksIdElements.Count -ne 9) {
        Write-Error "'$(aksId)'' is not a valid AKS resource id"
        exit 1
      }
      $aksName = $aksIdElements[8]
      $resourceGroupName = $aksIdElements[4]
      Write-Host "aksId: $(aksId)"
      Write-Host "aksName: ${aksName}"
      Write-Host "resourceGroupName: ${resourceGroupName}"
      Write-Host "##vso[task.setvariable variable=aksName;isOutput=true]${aksName}"
      Write-Host "##vso[task.setvariable variable=resourceGroupName;isOutput=true]${resourceGroupName}"
    displayName: 'Prepare variables'
    name: split

  - task: AzureCLI@2
    displayName: 'Inspect cluster'
    inputs:
      addSpnToEnvironment: true
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks show -n $(split.aksName) -g $(split.resourceGroupName) `
                    --query "{kubernetesVersion:kubernetesVersion, powerState:powerState.code, disableLocalAccounts:disableLocalAccounts, enableRbac:enableRbac, enableAzureRbac:aadProfile.enableAzureRbac, fqdn:fqdn, privateFqdn:privateFqdn, publicNetworkAccess:publicNetworkAccess, outboundType:networkProfile.outboundType, provisioningState:provisioningState}" `
                    | ConvertFrom-Json `
                    | Set-Variable cluster
        
        $cluster | Format-List
        if (!($cluster.enableAzureRbac)) {
          Write-Host "##vso[task.logissue type=error]Azure RBAC is not enabled on $(split.aksName)"
          exit 1
        }

        Write-Host "`nAKS role assignments for the service connection:"
        az role assignment list --assignee $env:servicePrincipalId `
                                --include-inherited `
                                --scope $(aksId) `
                                --query "[].{Role:roleDefinitionName, Scope:scope}" `
                                -o json `
                                | ConvertFrom-Json `
                                | Set-Variable roleAssignments
        $roleAssignments | Format-Table -AutoSize
        $roleAssignments | Where-Object {$_.Role -imatch "Kubernetes.*RBAC"} | Set-Variable aksRoleAssignments
        if ($aksRoleAssignments.Count -eq 0) {
          Write-Host "##vso[task.logissue type=warning]No AKS RBAC assignments found on $(split.aksName) for the Service Connection"
        }

        if ($cluster.powerState -ne "Running") {
          Write-Host "Starting cluster..."
          az aks wait  -n $(split.aksName) -g $(split.resourceGroupName) --updated
          az aks start -n $(split.aksName) -g $(split.resourceGroupName)
          az aks wait  -n $(split.aksName) -g $(split.resourceGroupName) --updated
        }

  # https://learn.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts
  - task: AzureCLI@2
    displayName: 'Disable local accounts'
    name: localAccounts
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks show -n $(split.aksName) -g $(split.resourceGroupName) --query "disableLocalAccounts" | Set-Variable disableLocalAccounts
        if ($disableLocalAccounts -ne "true") {
          Write-Host "`nDisabling local accounts on $(split.aksName)..."
          az aks update -n $(split.aksName) -g $(split.resourceGroupName) --disable-local-accounts
        } else {
          Write-Host "Local accounts are already enabled on $(split.aksName)"
        }
        Write-Host "##vso[task.setvariable variable=disableLocalAccountsOriginalState;isOutput=true]${disableLocalAccounts}"

- job: kubectlLocalAccountsDisabled
  dependsOn: inspectCluster
  displayName: 'kubectl (local accounts disabled)'
  variables:
    aksName: $[ dependencies.inspectCluster.outputs['split.aksName'] ]
    resourceGroupName: $[ dependencies.inspectCluster.outputs['split.resourceGroupName'] ]
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: KubeloginInstaller@0

  - task: AzureCLI@2
    displayName: 'kubectl with kubelogin (azure cli)'
    timeoutInMinutes: 1
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        kubectl config unset contexts.$(aksName)
        kubectl config unset contexts.$(aksName)-admin
        kubelogin remove-tokens
        
        az aks get-credentials -n $(aksName) -g $(resourceGroupName) --overwrite-existing
        kubelogin convert-kubeconfig -l azurecli

        kubectl config view
        kubectl cluster-info
        kubectl get nodes

  # Fails as admin credentials are not available when local accounts are disabled
  - task: AzureCLI@2
    continueOnError: true 
    displayName: 'kubectl admin (fails when local accounts are disabled)'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        kubectl config unset contexts.$(aksName)
        kubectl config unset contexts.$(aksName)-admin

        Write-Host "##vso[task.logissue type=warning]The next command (az aks get-credentials) will fail as admin credentials are not available when local accounts are disabled"
        az aks get-credentials -n $(aksName) -g $(resourceGroupName) --overwrite-existing -a

        kubectl config view
        kubectl cluster-info
        kubectl get nodes

- job: kubectlTaskLocalAccountsDisabled
  dependsOn: inspectCluster
  displayName: 'Kubernetes@1 (local accounts disabled)'
  variables:
    aksName: $[ dependencies.inspectCluster.outputs['split.aksName'] ]
    resourceGroupName: $[ dependencies.inspectCluster.outputs['split.resourceGroupName'] ]
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: KubeloginInstaller@0

  - task: Kubernetes@1
    displayName: 'Kubernetes@1'
    timeoutInMinutes: 1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: $(subscriptionConnection)
      azureResourceGroup: $(resourceGroupName)
      kubernetesCluster: $(aksName)
      command: 'get'
      arguments: nodes
      useClusterAdmin: false

  # Fails as admin credentials are not available when local accounts are disabled
  - task: Kubernetes@1
    continueOnError: true
    displayName: 'Kubernetes@1 admin (fails when local accounts are disabled)'
    enabled: true
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: $(subscriptionConnection)
      azureResourceGroup: $(resourceGroupName)
      kubernetesCluster: $(aksName)
      command: 'get'
      arguments: nodes
      useClusterAdmin: true


- job: enableLocalAccounts
  condition: and(succeededOrFailed(),ne(coalesce(dependencies.inspectCluster.outputs['localAccounts.disableLocalAccountsOriginalState'],'empty'),'empty'))
  dependsOn: 
  - inspectCluster
  - kubectlLocalAccountsDisabled
  - kubectlTaskLocalAccountsDisabled
  displayName: 'Enable Local Accounts'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    aksName: $[ dependencies.inspectCluster.outputs['split.aksName'] ]
    resourceGroupName: $[ dependencies.inspectCluster.outputs['split.resourceGroupName'] ]
  steps:
  - task: AzureCLI@2
    displayName: 'Enable local accounts'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Write-Host "`nEnabling local accounts on $(aksName)..."
        az aks wait   -n $(aksName) -g $(resourceGroupName) --updated
        az aks update -n $(aksName) -g $(resourceGroupName) --enable-local-accounts
        az aks wait   -n $(aksName) -g $(resourceGroupName) --updated


- job: kubectlLocalAccountsEnabled
  condition: and(succeededOrFailed(),ne(coalesce(dependencies.inspectCluster.outputs['localAccounts.disableLocalAccountsOriginalState'],'empty'),'empty'))
  dependsOn: 
  - inspectCluster
  - enableLocalAccounts
  displayName: 'kubectl (local accounts enabled)'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    aksName: $[ dependencies.inspectCluster.outputs['split.aksName'] ]
    resourceGroupName: $[ dependencies.inspectCluster.outputs['split.resourceGroupName'] ]
  steps:
  # Works as admin credentials are used and kubelogin is not needed
  - task: AzureCLI@2
    displayName: 'kubectl admin'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        kubectl config unset contexts.$(aksName)
        kubectl config unset contexts.$(aksName)-admin

        az aks get-credentials -n $(aksName) -g $(resourceGroupName) --overwrite-existing -a

        kubectl config view
        kubectl cluster-info
        kubectl get nodes

  - task: KubeloginInstaller@0

  - task: AzureCLI@2
    displayName: 'kubectl with kubelogin (azure cli)'
    timeoutInMinutes: 1
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        kubectl config unset contexts.$(aksName)
        kubectl config unset contexts.$(aksName)-admin
        kubelogin remove-tokens
        
        az aks get-credentials -n $(aksName) -g $(resourceGroupName) --overwrite-existing
        kubelogin convert-kubeconfig -l azurecli

        kubectl config view
        kubectl cluster-info
        kubectl get nodes


- job: kubectlTaskLocalAccountsEnabled
  condition: and(succeededOrFailed(),ne(coalesce(dependencies.inspectCluster.outputs['localAccounts.disableLocalAccountsOriginalState'],'empty'),'empty'))
  dependsOn: 
  - inspectCluster
  - enableLocalAccounts
  displayName: 'Kubernetes@1 (local accounts enabled)'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    aksName: $[ dependencies.inspectCluster.outputs['split.aksName'] ]
    resourceGroupName: $[ dependencies.inspectCluster.outputs['split.resourceGroupName'] ]
  steps:
  # Works as admin credentials are used and kubelogin is not needed
  - task: Kubernetes@1
    displayName: 'Kubernetes@1 admin'
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: $(subscriptionConnection)
      azureResourceGroup: $(resourceGroupName)
      kubernetesCluster: $(aksName)
      command: 'get'
      arguments: nodes
      useClusterAdmin: true

  - task: KubeloginInstaller@0

  - task: Kubernetes@1
    displayName: 'Kubernetes@1 (with kubelogin)'
    timeoutInMinutes: 1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: $(subscriptionConnection)
      azureResourceGroup: $(resourceGroupName)
      kubernetesCluster: $(aksName)
      command: 'get'
      arguments: nodes
      useClusterAdmin: false

- job: reDisableLocalAccounts
  condition: and(succeededOrFailed(),eq(coalesce(dependencies.inspectCluster.outputs['localAccounts.disableLocalAccountsOriginalState'],'false'),'true'),ne(coalesce(dependencies.inspectCluster.outputs['localAccounts.disableLocalAccountsOriginalState'],'empty'),'empty'))
  dependsOn: 
    - inspectCluster
    - kubectlLocalAccountsEnabled
    - kubectlTaskLocalAccountsEnabled
  displayName: 'Disable Local Accounts'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    aksName: $[ dependencies.inspectCluster.outputs['split.aksName'] ]
    resourceGroupName: $[ dependencies.inspectCluster.outputs['split.resourceGroupName'] ]
  steps:
  - task: AzureCLI@2
    displayName: 'Re-disable local accounts'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Write-Host "`nDisabling local accounts on $(aksName)..."
        az aks wait   -n $(aksName) -g $(resourceGroupName) --updated
        az aks update -n $(aksName) -g $(resourceGroupName) --disable-local-accounts
        az aks wait   -n $(aksName) -g $(resourceGroupName) --updated
