trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main


variables:
- group: 'kubernetes' # should contain subscriptionConnection, aksId
# - name: 'aksIdElements'
#   value: $[ split(variables['aksId'], '/') ]
- name: 'aksIdVar'
  value: $[ variables['aksId'] ]
- name: 'aksName'
  # value: $[ split(variables['aksId'], '/')[8] ]
  value: $[ split('/1/2/3/4/5/6/7/8/9/0', '/')[8] ]
- name: 'resourceGroupName'
  value: $[ split(variables['aksId'], '/')[4] ]

jobs:
- job: agent
  displayName: 'Kubernetes tasks'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - pwsh: |
      Write-Host "aksId: $(aksId)"
      Write-Host "aksIdVar: $(aksIdVar)"
      # Write-Host "aksIdElements: $(aksIdElements)"
      Write-Host "aksName: $(aksName)"
      Write-Host "resourceGroupName: $(resourceGroupName)"
    displayName: 'Display variables'

  - task: AzureCLI@2
    displayName: 'Access AKS'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks get-credentials -n $(aksName) -g $(resourceGroupName) -a

        kubectl config view
        kubectl cluster-info
        kubectl get nodes

  - task: AzureCLI@2
    displayName: 'Install kubelogin'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az aks install-cli --kubelogin-version latest
