trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

resources:
  repositories:
  - repository: modules
    type: git
    name: PipelineSamples/terraform-modules-sample

steps:
- checkout: self

- checkout: modules
  fetchDepth: 1
  persistCredentials: true

- pwsh: |
    terraform init
    terraform apply -auto-approve
  displayName: 'Terraform apply'
  workingDirectory: azure-pipeline-examples/deployment/terraform-modules