trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

# variables:
#   - group: 'terraform-modules' # should populate organizationName, projectName and repositoryName

pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: modules
    type: git
    name: PipelineSamples/terraform-modules-sample

steps:
- checkout: self

- checkout: modules
  fetchDepth: 1
  persistCredentials: true

- pwsh: |

    # git config --global url."https://user:$(System.AccessToken)@dev.azure.com/ericvan/PipelineSamples".insteadOf "https://dev.azure.com/ericvan/PipelineSamples" # May not work with HTTP/2
    # git -c http.extraheader="Authorization: bearer $(System.AccessToken)"
    # git config --global http.https://ericvan@dev.azure.com.extraheader "Authorization: bearer $(System.AccessToken)"
    git config --global http.https://dev.azure.com/ericvan/PipelineSamples.extraheader "Authorization: bearer $(System.AccessToken)"

    Get-Content /home/vsts/.gitconfig

    terraform init
    terraform apply -auto-approve

    git config --global --unset-all http.https://dev.azure.com/ericvan/PipelineSamples.extraheader
  displayName: 'Terraform apply'
  # workingDirectory: deployment/terraform-modules
  workingDirectory: azure-pipeline-examples/deployment/terraform-modules