trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

resources:
  repositories:
  - repository: modules
    type: git
    name: PipelineSamples/terraform-modules-sample

steps:
- checkout: self

- checkout: modules
  persistCredentials: true

- pwsh: |
    ls -alR
    # terraform init
    # terraform apply -auto-approve
  workingDirectory: deployment/terraform-modules