parameters:
- name: pool
  displayName: Agent Pool
  type: string
  default: 'Azure Pipelines'
- name: serviceConnection
  displayName: Override Service Connection
  type: string
  default: 'my-azure-subscription'
- name: vmssName
  displayName: VMSS Name
  type: string
- name: vmssOsType
  displayName: OS
  type: string
  default: Linux
  values:
  - Linux
  - Windows
- name: customScriptsStorageAccount
  displayName: 'Custom Scripts Storage Account'
  type: string


trigger: none

jobs:
- job: rbacTest
  displayName: 'RBAC Tests'

  pool:
    name: '${{ parameters.pool }}'
    vmImage: ubuntu-latest
    
  steps:
  # https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-vmss-deployment
  - task: AzureVmssDeployment@0
    inputs:
      azureSubscription: '${{ parameters.serviceConnection }}'
      action: 'Configure application startup'
      vmssName: '${{ parameters.vmssName }}'
      vmssOsType: '${{ parameters.vmssOsType }}'
      customScriptsDirectory: '$(Build.SourcesDirectory)/tasks/AzureVmssDeployment/scripts'
      customScript: |
        lsb_release -d
      customScriptsStorageAccount: '${{ parameters.customScriptsStorageAccount }}'
      skipArchivingCustomScripts: false
