trigger:
  branches:
    include:
    - '*'

extends:
  template: start.yml
  # template: ../script-check2/template.yml
  parameters:
    buildSteps:  
    # usersteps:  
      - bash: echo Test #Passes
        displayName: succeed
      - bash: echo "Test"
        displayName: succeed
      - task: CmdLine@2
        displayName: Test 3 - Will Fail
        inputs:
          script: echo "Script Test"