# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

jobs:
- job: 
  strategy:
    matrix:
      # macOS:
      #   vmImage: 'macos-latest'
      Ubuntu:
        vmImage: 'ubuntu-latest'
      Windows:
        vmImage: 'windows-latest'
    maxParallel: 3
  pool:
    vmImage: $(vmImage)
  steps:
  - pwsh: |
      echo $env:AGENT_TOOLSDIRECTORY
      dir $env:AGENT_TOOLSDIRECTORY
