name: terraform-service-connection

parameters:
- name: serviceConnection
  displayName: Azure Service Connection Name
  type: string
  default: my-azure-subscription

trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
# - job: terraformSingleStep
#   displayName: 'Invoke Terraform with Azure CLI inherited service connection in the same step'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#     - task: TerraformInstaller@0
#       displayName: 'Install Terraform'
#       inputs:
#         terraformVersion: 'latest'
#     - task: AzureCLI@2
#       displayName: 'Terraform with Azure CLI task'
#       inputs:
#         azureSubscription: '${{ parameters.serviceConnection }}'
#         scriptType: bash
#         scriptLocation: inlineScript
#         inlineScript: |
#           # Inherit Azure CLI service connection
#           export ARM_CLIENT_ID=$servicePrincipalId
#           export ARM_CLIENT_SECRET=$servicePrincipalKey
#           export ARM_TENANT_ID=$tenantId
#           export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
#           env | grep "^ARM_" # SPN values will be masked

#           terraform init
#           terraform apply -auto-approve

#         addSpnToEnvironment: true
#         useGlobalConfig: true
#         failOnStandardError: true
#         workingDirectory: '$(Build.SourcesDirectory)/ubuntu/terraform-service-connection'

- job: terraformMultiStep
  displayName: 'Invoke Terraform with Azure CLI inherited service connection in a subsequent step'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'
    - task: AzureCLI@2
      displayName: 'Azure CLI'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Inherit Azure CLI service connection
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID;isoutput=true;issecret=true]$servicePrincipalId"
          echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;isoutput=true;issecret=true]$servicePrincipalKey"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID;isoutput=true]$tenantId"
          echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;isoutput=true]$(az account show --query id -o tsv)"
        addSpnToEnvironment: true
        useGlobalConfig: true
        failOnStandardError: true
    - bash: |
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        env | grep "^ARM_" # SPN values will be masked

        terraform init
        terraform apply -auto-approve
      displayName: Terraform
      failOnStandardError: true
      workingDirectory: '$(Build.SourcesDirectory)/ubuntu/terraform-service-connection'
