name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

trigger: none

jobs:
- job: 'azurepipelines'
  displayName: 'Azure Pipelines pool'
  
  variables:
    AGENT_DIAGNOSTIC: 'true'
    AZP_AGENT_USE_LEGACY_HTTP: 'true'
    VSTSAGENT_TRACE: 'true'
    VSTS_AGENT_HTTPTRACE: 'true'

  pool:
    name: 'Azure Pipelines'
    vmImage: ubuntu-latest
  steps:
  - bash: |
      printenv | sort