trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: 
  displayName: 'Test CDN access'
  strategy:
    matrix:
      # macOS:
      #   vmImage: 'macos-latest'
      Ubuntu:
        vmImage: 'ubuntu-latest'
      # Windows:
      #   vmImage: 'windows-latest'
    maxParallel: 3
  pool:
    vmImage: $(vmImage)
  steps:
  - pwsh: |
      $ErrorActionPreference = 'Stop'
      try {
        Invoke-WebRequest -Method HEAD `
                          -Uri https://download.agent.dev.azure.com/agent/health/probeZZ `
                          -TimeoutSec 1 `
                          -UseBasicParsing `
                          | Set-Variable response
        if ($response.StatusCode -lt 400) {
          Write-Host "Agent CDN is accessible. Status code: $($response.StatusCode)"
        } else {
          throw "Agent CDN is inaccessible"
        }
      } catch {
        Write-Warning "Exception"
        Write-Host "##vso[task.logissue type=warning]Can't access download.agent.dev.azure.com. Please make sure the access is not blocked by a firewall."
        Write-Warning "Agent CDN is inaccessible. Status code: $($response.StatusCode)"
        $response | Format-List
      }
    displayName: 'Test download.agent.dev.azure.com access'