name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

trigger: none

variables:
  AGENT_DIAGNOSTIC: 'true'
  AGENT_USE_NODE10: 'true'
  # AZP_AGENT_USE_LEGACY_HTTP: 'true' # self-hosted agents only
  VSTSAGENT_TRACE: 'true'
  VSTS_AGENT_HTTPTRACE: 'true'

jobs:
- job: 'azurepipelines'
  displayName: 'Azure Pipelines pool'
  
  pool:
    name: 'Azure Pipelines'
    vmImage: ubuntu-latest
  steps:
  - bash: |
      printenv | sort